### PR TITLE
Fix regex for custom messages module

### PR DESCRIPTION
**Pull request by exeto**
When you have an application that is listed lower in the registry than `ember-validations/messages`, custom messages module will fail

Reproduction steps:

1. Generate new ember app that starts with a lower alpha character - i.e `ember new zebra-app`
2. Install `ember-validations`
3. Install all dependencies needed for `ember-changeset-validations`
4. Provide a custom messages module i.e. - `zebra-app/app/validations/messages`
5. Try to use validations, and you will see that custom messages does not get used

Description taken from https://github.com/poteto/ember-changeset-validations/pull/144

### CODE REVIEW

**Comment by exeto** [comment]
@poteto Hi. This project is not supported?

**Comment by nucleartide** [comment]
@exeto Could you explain what this accomplishes? Sorry – I haven't looked through what this code does.

**Comment by exeto** [comment]
@nucleartide I updated the message.

**Comment by nucleartide** [comment]
@exeto Ahh, I see what you mean. The regex will match `ember-validations/messages` before it matches `zebra-app/validations/messages`.

I think a more robust solution would be to match on the app name directly. Would you mind modifying the regex to include `modulePrefix` or `APP.name` from `config/environment`? [This StackOverflow answer](https://stackoverflow.com/a/42011524/1112407) has some approaches to getting the `ENV`.

**Comment by exeto** [comment]
@nucleartide Done

**Comment by nucleartide** [comment]
@exeto Excellent work, thanks!

**Comment by exeto** [comment]
@nucleartide thanks

**Pull request merged**
