### PR TITLE
Move `ember-changeset` to `devDependencies`

### PR DESCRIPTION
**Pull request by SergeAstapov**
Closes # .

### CODE REVIEW

**Comment by snewcomer** [comment]
Is this to allow the consumer to put in their own?

**Comment by josemarluedke** [comment]
This is a nice change. It seems we don't import `ember-changeset` in the addon itself, just in the dummy app.

**Comment by SergeAstapov** [comment]
@snewcomer correct! As @josemarluedke said the `ember-changeset-validations` addon itself does not depend on `ember-changeset`, only in tests.

For the consuming app, there is not much value to bring this addon without `ember-changeset` but that should be responsibility of the app author to use or not use `ember-changeset`.

IMO this makes things crystal clear about "who does what".

May need to be have "breaking" label as technically, if someone did not install `ember-changeset` themselves their app may break.

**Comment by SergeAstapov** [comment]
build failure is the same as we have in master.
Need to land #335 to fix CI and then I'll rebase this PR.

**Comment by SergeAstapov** [comment]
@snewcomer this is ready to go! cc @josemarluedke

**Comment by snewcomer** [comment]
Probably some copyright to add to the README to indicate `ember-changeset` also needs to be installed along side this add-on?

**Comment by SergeAstapov** [comment]
@snewcomer done! Thanks for idea

**Pull request merged**
